###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "name": "xl",
  "password": "123456",
  "email": "762610973@qq.com",
  "gender": "男"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "xl",
  "password": "1234561"
}

###
GET http://localhost:8080/user/?page=1&page_size=10


###
DELETE http://localhost:8080/user/
Content-Type: application/json

{
  "ids": [1,2]
}
